from django import forms

class PredictorForm(forms.Form):
    itching = forms.BooleanField(required=False,initial=False)
    skin_rash = forms.BooleanField(required=False,initial=False)
    nodal_skin_eruptions = forms.BooleanField(required=False,initial=False)
    continuous_sneezing = forms.BooleanField(required=False,initial=False)
    shivering = forms.BooleanField(required=False,initial=False)
    chills = forms.BooleanField(required=False,initial=False)
    joint_pain = forms.BooleanField(required=False,initial=False)
    stomach_pain = forms.BooleanField(required=False,initial=False)
    acidity = forms.BooleanField(required=False,initial=False)
    ulcers_on_tongue = forms.BooleanField(required=False,initial=False)
    muscle_wasting = forms.BooleanField(required=False,initial=False)
    vomiting = forms.BooleanField(required=False,initial=False)
    burning_micturition = forms.BooleanField(required=False,initial=False)
    spotting_urination= forms.BooleanField(required=False,initial=False)
    fatigue = forms.BooleanField(required=False,initial=False)
    weight_gain = forms.BooleanField(required=False,initial=False)
    anxiety = forms.BooleanField(required=False,initial=False)
    cold_hands_and_feets = forms.BooleanField(required=False,initial=False)
    mood_swings = forms.BooleanField(required=False,initial=False)
    weight_loss = forms.BooleanField(required=False,initial=False)
    restlessness = forms.BooleanField(required=False,initial=False)
    lethargy = forms.BooleanField(required=False,initial=False)
    patches_in_throat = forms.BooleanField(required=False,initial=False)
    irregular_sugar_level = forms.BooleanField(required=False,initial=False)
    cough = forms.BooleanField(required=False,initial=False)
    high_fever = forms.BooleanField(required=False,initial=False)
    sunken_eyes = forms.BooleanField(required=False,initial=False)
    breathlessness = forms.BooleanField(required=False,initial=False)
    sweating = forms.BooleanField(required=False,initial=False)
    dehydration = forms.BooleanField(required=False,initial=False)
    indigestion = forms.BooleanField(required=False,initial=False)
    headache = forms.BooleanField(required=False,initial=False)
    yellowish_skin= forms.BooleanField(required=False,initial=False)
    dark_urine= forms.BooleanField(required=False,initial=False)
    nausea= forms.BooleanField(required=False,initial=False)
    loss_of_appetite= forms.BooleanField(required=False,initial=False)
    pain_behind_the_eyes= forms.BooleanField(required=False,initial=False)
    back_pain= forms.BooleanField(required=False,initial=False)
    constipation= forms.BooleanField(required=False,initial=False)
    abdominal_pain= forms.BooleanField(required=False,initial=False)
    diarrhoea= forms.BooleanField(required=False,initial=False)
    mild_fever= forms.BooleanField(required=False,initial=False)
    yellow_urine= forms.BooleanField(required=False,initial=False)
    yellowing_of_eyes= forms.BooleanField(required=False,initial=False)
    acute_liver_failure= forms.BooleanField(required=False,initial=False)
    fluid_overload= forms.BooleanField(required=False,initial=False)
    swelling_of_stomach= forms.BooleanField(required=False,initial=False)
    swelled_lymph_nodes= forms.BooleanField(required=False,initial=False)
    malaise= forms.BooleanField(required=False,initial=False)
    blurred_and_distorted_vision= forms.BooleanField(required=False,initial=False)
    phlegm= forms.BooleanField(required=False,initial=False)
    throat_irritation= forms.BooleanField(required=False,initial=False)
    redness_of_eyes= forms.BooleanField(required=False,initial=False)
    sinus_pressure= forms.BooleanField(required=False,initial=False)
    runny_nose= forms.BooleanField(required=False,initial=False)
    congestion= forms.BooleanField(required=False,initial=False)
    chest_pain= forms.BooleanField(required=False,initial=False)
    weakness_in_limbs= forms.BooleanField(required=False,initial=False)
    fast_heart_rate= forms.BooleanField(required=False,initial=False)
    pain_during_bowel_movements= forms.BooleanField(required=False,initial=False)
    pain_in_anal_region= forms.BooleanField(required=False,initial=False)
    bloody_stool= forms.BooleanField(required=False,initial=False)
    irritation_in_anus= forms.BooleanField(required=False,initial=False)
    neck_pain= forms.BooleanField(required=False,initial=False)
    dizziness= forms.BooleanField(required=False,initial=False)
    cramps= forms.BooleanField(required=False,initial=False)
    bruising= forms.BooleanField(required=False,initial=False)
    obesity= forms.BooleanField(required=False,initial=False)
    swollen_legs= forms.BooleanField(required=False,initial=False)
    swollen_blood_vessels= forms.BooleanField(required=False,initial=False)
    puffy_face_and_eyes= forms.BooleanField(required=False,initial=False)
    enlarged_thyroid= forms.BooleanField(required=False,initial=False)
    brittle_nails= forms.BooleanField(required=False,initial=False)
    swollen_extremeties= forms.BooleanField(required=False,initial=False)
    excessive_hunger= forms.BooleanField(required=False,initial=False)
    extra_marital_contacts= forms.BooleanField(required=False,initial=False)
    drying_and_tingling_lips= forms.BooleanField(required=False,initial=False)
    slurred_speech= forms.BooleanField(required=False,initial=False)
    knee_pain= forms.BooleanField(required=False,initial=False)
    hip_joint_pain= forms.BooleanField(required=False,initial=False)
    muscle_weakness= forms.BooleanField(required=False,initial=False)
    stiff_neck= forms.BooleanField(required=False,initial=False)
    swelling_joints= forms.BooleanField(required=False,initial=False)
    movement_stiffness= forms.BooleanField(required=False,initial=False)
    spinning_movements= forms.BooleanField(required=False,initial=False)
    loss_of_balance= forms.BooleanField(required=False,initial=False)
    unsteadiness= forms.BooleanField(required=False,initial=False)
    weakness_of_one_body_side= forms.BooleanField(required=False,initial=False)
    loss_of_smell= forms.BooleanField(required=False,initial=False)
    bladder_discomfort= forms.BooleanField(required=False,initial=False)
    foul_smell_of= forms.BooleanField(required=False,initial=False)
    continuous_feel_of_urine= forms.BooleanField(required=False,initial=False)
    passage_of_gases= forms.BooleanField(required=False,initial=False)
    internal_itching= forms.BooleanField(required=False,initial=False)
    toxic_look_typhos= forms.BooleanField(required=False,initial=False)
    depression = forms.BooleanField(required=False,initial=False)
    irritability= forms.BooleanField(required=False,initial=False)
    muscle_pain= forms.BooleanField(required=False,initial=False)
    altered_sensorium= forms.BooleanField(required=False,initial=False)
    red_spots_over_body= forms.BooleanField(required=False,initial=False)
    belly_pain= forms.BooleanField(required=False,initial=False)
    abnormal_menstruation= forms.BooleanField(required=False,initial=False)
    dischromic_patches= forms.BooleanField(required=False,initial=False)
    watering_from_eyes= forms.BooleanField(required=False,initial=False)
    increased_appetite= forms.BooleanField(required=False,initial=False)
    polyuria= forms.BooleanField(required=False,initial=False)
    family_history= forms.BooleanField(required=False,initial=False)
    mucoid_sputum= forms.BooleanField(required=False,initial=False)
    rusty_sputum= forms.BooleanField(required=False,initial=False)
    lack_of_concentration= forms.BooleanField(required=False,initial=False)
    visual_disturbances= forms.BooleanField(required=False,initial=False)
    receiving_blood_transfusion= forms.BooleanField(required=False,initial=False)
    receiving_unsterile_injections= forms.BooleanField(required=False,initial=False)
    coma= forms.BooleanField(required=False,initial=False)
    stomach_bleeding= forms.BooleanField(required=False,initial=False)
    distention_of_abdomen= forms.BooleanField(required=False,initial=False)
    history_of_alcohol_consumption= forms.BooleanField(required=False,initial=False)
    fluid_overload_1= forms.BooleanField(required=False,initial=False)
    blood_in_sputum= forms.BooleanField(required=False,initial=False)
    prominent_veins_on_calf= forms.BooleanField(required=False,initial=False)
    palpitations= forms.BooleanField(required=False,initial=False)
    painful_walking= forms.BooleanField(required=False,initial=False)
    pus_filled_pimples= forms.BooleanField(required=False,initial=False)
    blackheads= forms.BooleanField(required=False,initial=False)
    scurring= forms.BooleanField(required=False,initial=False)
    skin_peeling= forms.BooleanField(required=False,initial=False)
    silver_like_dusting= forms.BooleanField(required=False,initial=False)
    small_dents_in_nails= forms.BooleanField(required=False,initial=False)
    inflammatory_nails= forms.BooleanField(required=False,initial=False)
    blister= forms.BooleanField(required=False,initial=False)
    red_sore_around_nose= forms.BooleanField(required=False,initial=False)
    yellow_crust_ooze= forms.BooleanField(required=False,initial=False)
