# Generated by Django 2.2.4 on 2020-07-06 08:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='symptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('itching', 'itching'), ('skin_rash', 'skin_rash'), ('nodal_skin_eruptions', 'nodal_skin_eruptions'), ('continuous_sneezing', 'continuous_sneezing'), ('shivering', 'shivering')], max_length=68),
        ),
    ]
